### ISSUE TITLE
请问png格式的医学图像可以用这个实现吗？

### ISSUE THREAD

**Issue by Chang12183** [DLWK/EANet#2]

**Comment by DLWK** [comment]
可以的，只要是针对分割的数据，基本都可以。  模型我们已经公开， 你只要单独写一下你自己的数据集的dataloader,  或者参考我们的代码。   就可以直接跑起来。 具体细节要根据自己的任务来修改代码。

**Comment by zhang257** [comment]
models.models中from .norm import Norm2d报错 怎么解决这个问题啊 求帅哥回复

**Comment by DLWK** [comment]
> models.models中from .norm import Norm2d报错 怎么解决这个问题啊 求帅哥回复

注释掉就可以了。 （*建议依据模型来修正代码）。最近比较忙，等有空的时间，我好好修正一下代码。

**Comment by zhang257** [comment]
感谢帅哥百忙之中的答复，看得出来这是一个good paper，我对这篇文章十分感兴趣。但是还是想请问一下，models.models中定义的EAnet中SAPP模块，up模块和outconv都显示报错，是不是存在其他的文件中，没有找到导入的文件。希望帅哥可以指导一下。

**Comment by DLWK** [comment]
> 感谢帅哥百忙之中的答复，看得出来这是一个good paper，我对这篇文章十分感兴趣。但是还是想请问一下，models.models中定义的EAnet中SAPP模块，up模块和outconv都显示报错，是不是存在其他的文件中，没有找到导入的文件。希望帅哥可以指导一下。

我重新上传models ,  应该可以解决大部分问题了。
