### ISSUE TITLE
关于复现EANet的一些问题

### ISSUE THREAD

**Issue by zhang257** [DLWK/EANet#3]
感谢帅哥的开源代码，我是也是做图像分割方向的，所以才会来打扰帅哥。
帅哥的代码有清楚的注释，便于学习，实在是业内的良心。
由于之前问问题没有总结到位，几次打扰到您，实在是不好意思。由于缺少一些包，自己写了点评价指标的代码，现在代码可以实现训练验证了，但是想尽可能的复现帅哥的代码运用在自己的数据集上，所以还是想得到帅哥的源码。
缺少的包总结，如以下：1：utils.metric包。2:evaluation文件。
最后帅哥可以提供一份可以测试训练权重的代码吗，看了一下，现在的包里面只有训练和验证的代码，如果能够提供，那实在是太棒了。
最后祝帅哥天天开心，多发top期刊论文。

**Comment by DLWK** [comment]
> 感谢帅哥的开源代码，我是也是做图像分割方向的，所以才会来打扰帅哥。 帅哥的代码有清楚的注释，便于学习，实在是业内的良心。 由于之前问问题没有总结到位，几次打扰到您，实在是不好意思。由于缺少一些包，自己写了点评价指标的代码，现在代码可以实现训练验证了，但是想尽可能的复现帅哥的代码运用在自己的数据集上，所以还是想得到帅哥的源码。 缺少的包总结，如以下：1：utils.metric包。2:evaluation文件。 最后帅哥可以提供一份可以测试训练权重的代码吗，看了一下，现在的包里面只有训练和验证的代码，如果能够提供，那实在是太棒了。 最后祝帅哥天天开心，多发top期刊论文。

回答：  1：utils.metric包   注释掉（没用），     2. 已添加evaluation文件，   3.  已上传提供test代码。需要你适当修正。
以上应该可以解决你大部分问题。     
最近确实非常忙，一年前的代码，确实有点粗糙，没有时间去整理，  等后期有时间我再好好的修正全部代码。 祝好！

**Comment by scwuchung** [comment]
> 

你好，请问你的数据集的edge标签是怎么得到的？
