### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by scwuchung** [DLWK/EANet#4]
作者大大你好，请问LIDC肺结节分割是用的哪个dataloader呢，LIDC数据集好像是3D的，模型好像输入是2D的，需要做怎样的处理才能用于训练呢，可以提供这部分处理的代码吗，或者有没有能参考的教程?谢谢

**Comment by DLWK** [comment]
感谢，关注 我们的LIDC数据是首先预先处理为2Dslice，  然后划分五折， 最后进行网络训练。  这部分代码网上应该有资源可以利用。

**Comment by scwuchung** [comment]
> 感谢，关注 我们的LIDC数据是首先预先处理为2Dslice， 然后划分五折， 最后进行网络训练。 这部分代码网上应该有资源可以利用。
你好，请问肺结节数据集的edge标签是怎么得到的，我现在处理后只有mask标签。
