### ISSUE TITLE
数据集中的edge标签

### ISSUE THREAD

**Issue by scwuchung** [DLWK/EANet#5]
很抱歉打扰作者大大，请问数据集中的edge标签是怎么获得的，我是用的是LUNA16数据集，标签只有mask图像，edge的边缘标签是怎么处理的，希望作者大大解答一下，万分感谢！

**Comment by DLWK** [comment]
请参照代码：EANet   /    utils.py    文件。获得边缘标签。祝好！

**Comment by scwuchung** [comment]
> 请参照代码：EANet / utils.py 文件。获得边缘标签
感谢作者，真的很敬业！
