### ISSUE TITLE
关于评价指标的问题，dice =0.0

### ISSUE THREAD

**Issue by scwuchung** [DLWK/EANet#6]
作者你好，不好意思又来打扰你了，在每轮训练完成之后的测试部分，评价指标除了acc是正常的，其他指标均为0，我将pred和label保存下来，发现从图片上看无论位置和大小也比较相似，但指标却总为0，感觉很疑惑，大佬能给些建议吗?谢谢！

**Comment by DLWK** [comment]
你好，通过你的问题，你检查一下你的pytorch的版本是不是1.1版本，和匹配的组件。这份代码是基于这个环境写入的。你尝试一下。希望问题可以解决。祝好！

**Comment by scwuchung** [comment]
感谢作者回答，问题已解决
