### ISSUE TITLE
关于Decoder

### ISSUE THREAD

**Issue by YaoCheng39** [DLWK/EANet#7]
论文中Decoder部分没有像传统的UNet结构使用自底向上结构，
而是使用了自顶向下结构，请问为什么要这样做啊，有没有消融实验可以对比一下。

**Comment by DLWK** [comment]
感谢关注，我们的方法使用了UNet结构使用自底向上结构（primal regression），为了更好学习特征表示和减少信息流失（传统下采样弊端），又设计了自顶向下结构（auxiliary deep regression）的信息回流。 形成了封闭的闭环形式。（借鉴深监督和自监督思想）  即MPR模块。消融实验验证了MPR模块的有效性。

**Comment by YaoCheng39** [comment]
您好，但是我看上传代码的代码decoder部分只有自顶向下的操作，没有找到自底向上的回流操作，请您指点。

**Comment by DLWK** [comment]
![image](https://user-images.githubusercontent.com/54352624/173806677-2e95cc41-1642-4a6e-90a7-2b66561184a6.png)

**Comment by DLWK** [comment]
![image](https://user-images.githubusercontent.com/54352624/173807340-20d54918-238d-45f3-82fe-ff692e99177d.png)

**Comment by YaoCheng39** [comment]
谢谢啦，看懂了
