### ISSUE TITLE
关于edge attention可视化 

### ISSUE THREAD

**Issue by klkl2164** [DLWK/EANet#8]
作者您好，请问您论文如下图所示的edge attention图是如何如何可视化出来的？是直接将特征图保存为灰度图然后进行色彩变化得到这种效果的吗？
![图片](https://github.com/DLWK/EANet/assets/134592602/1da6d682-a312-489b-9bc1-739e0cbdfb7f)
如果我想可视化的话是不是要将EANet/models /models.py中133行的 edge_out保存为图片？

**Comment by DLWK** [comment]
您好，谢谢关注我们的工作，可以利用相关代码可视化   heatmapshow = cv2.applyColorMap(output, cv2.COLORMAP_JET)

**Comment by klkl2164** [comment]
> 您好，谢谢关注我们的工作，可以利用相关代码可视化 heatmapshow = cv2.applyColorMap(output, cv2.COLORMAP_JET)

非常感谢您的回复！
